### ISSUE TITLE
Python 3.11 test failure

### ISSUE THREAD

**Issue by bcail** [django-compressor/django-compressor#1158]
I'm seeing `OfflineCompressTestCaseWithLazyStringAlikeUrls` test failures under Python 3.11. Bisecting the Python 3.11 branch showed that the https://github.com/python/cpython/commit/76cd81d60310d65d01f9d7b48a8985d8ab89c8b4 commit introduced the issue.

I tried commenting out the `@functools.lru_cache(typed=True)` line from the `urlsplit` function in the Python 3.11 branch, and that seemed to fix the test. Does there need to be a `clear_cache()` call, or some other way to deal with the `urlsplit` cache in Python 3.11?

**Comment by diox** [comment]
I was able to reproduce in https://github.com/django-compressor/django-compressor/pull/1168, I'll take a look.

**Comment by diox** [comment]
So, this problem is because of our support for lazy `STATIC_URL` / `COMPRESS_URL` introduced in  #876. Indeed a couple `clear_cache()` calls in tests fixes the problem, but I'm not sure it's a good idea... it will likely fail in real life with such lazy settings - they are passed by something (haven't bothered to look what yet) to `urlsplit` while still being lazy, so it caches the call with the lazy function... We can maybe find a workaround, but I'm not even sure this works correctly with Django alone today with Python 3.11.

**Comment by diox** [comment]
Figured out a fix for the tests in https://github.com/django-compressor/django-compressor/pull/1168/commits/eb1a7283f1700987d132d39a507cd9ea8fc6f15d

I still think this is dangerous, things can easily break depending on implementation of the lazy wrapper, but given that the fix is trivial we can keep this in compressor for now.
