### ISSUE TITLE
CssAbsoluteFilter only seems to ever work with settings.DEBUG enabled

### ISSUE THREAD

**Issue by patrys** [django-compressor/django-compressor#467]
We have a virtualenv that holds a project and its dependencies. All dependencies use `django.contrib.staticfiles` and the files in question are deployed directly to S3.

The checks at the beginning of the `input()` method of `CssAbsoluteFilter` to always fail.

Relevant code:

``` python
class CssAbsoluteFilter(FilterBase):

    # ...

    def input(self, filename=None, basename=None, **kwargs):
        if filename is not None:
            filename = os.path.normcase(os.path.abspath(filename))
        if (not (filename and filename.startswith(self.root)) and
                not self.find(basename)):
            # this will always fail:
            # filename = '/opt/envs/foo/src/some-dependency/app/static/css/example.css'
            # self.root = '/opt/envs/foo/src/project/static'
            return self.content
        # ...

    def find(self, basename):
        # settings.DEBUG is False so this method is irrelevant
        if settings.DEBUG and basename and staticfiles.finders:
            return staticfiles.finders.find(basename)
```

Why does it need to check whether the file lives inside of `COMPRESS_ROOT` if it seems to be mainly an output directory?

**Comment by chriskief** [comment]
I'm also making use of S3 / remote storages and it should be noted that this change will break existing implementations that rely on the old behavior where relative URLs were present in the compressed css.

In the current version, if you have the following code:

```
url("../images/example/image.png")
```

The compressed file will also have a relative URL, if ```filename``` does not start with ```self.root```:

```
url("../images/example/image.png")
```

This is because, as @patrys pointed out, the following check will always fail under those conditions:

```python
# filename = /local/path/to/root/myapp/static/css/styles.scss
# self.root = /local/path/to/root/static/temp
if (not (filename and filename.startswith(self.root)) and not self.find(basename)):
```

With this change, the url will now be an absolute URL, and depending on your configuration, the generated path may be incorrect.

In my case, the URL went from a relative URL in the compressed file to:

```
url('https://abcdefg.cloudfront.net/static/css/pages/images/example/image.png')
```

When it really needs to be the following:

```
url('https://abcdefg.cloudfront.net/static/images/example/image.png')
```

Notice the extra ```/css/pages``` in the first absolute URL vs. the second. This is due to the absolute URL being derived from the relative URL of the asset as noted by @agriffis.

I haven't tried to adjust my settings yet to reflect the #467 changes, but please be aware that this change will definitely cause some existing implementations to break.
