### ISSUE TITLE
Switch tests altering settings manually to @override_settings

### ISSUE THREAD

**Issue by diox** [django-compressor/django-compressor#669]
I did some cleaning in #667 but we still have a few tests left altering settings manually instead of using `@override_settings`. Let's fix them.

A quick grep (might be incomplete) found:

```
compressor/tests/test_templatetags.py:        settings.COMPRESS_ENABLED = True
compressor/tests/test_templatetags.py:        settings.COMPRESS_PRECOMPILERS = (
compressor/tests/test_filters.py:        settings.COMPRESS_CSS_HASHING_METHOD = self.hashing_method
compressor/tests/test_parsers.py:        settings.COMPRESS_PARSER = self.parser_cls
compressor/tests/test_base.py:        settings.COMPRESS_ENABLED = True
compressor/tests/test_base.py:        settings.COMPRESS_PRECOMPILERS = ()
compressor/tests/test_base.py:        settings.COMPRESS_DEBUG_TOGGLE = 'nocompress'
compressor/tests/test_base.py:        settings.COMPRESS_VERBOSE = True
```

**Comment by karyon** [comment]
i made a branch ready which fixes this, but it made this mess even messier because i needed to introduce self.override_settings2 to keep testcase subclasses from overwriting their superclasses' self.override_settings.

when support for django 1.4 is dropped, we can probably just use the override_settings decorator on the TestCase classes and it should just work. so i'd wait for that.

**Comment by diox** [comment]
@karyon : we've now dropped 1.4 support, care to submit a pull request to fix this ?

**Comment by karyon** [comment]
yeah, i'll probably do it in the next couple days.
