### ISSUE TITLE
embedded null byte

### ISSUE THREAD

**Issue by shacker** [django-compressor/django-compressor#789]
Our app was experiencing  mysterious and random/intermittent crashing, with an "embedded null byte" error in the stack trace that didn't point to any of our own code - it seemed to come from the virtualenv itself. I was unable to debug, asked [this question](http://stackoverflow.com/questions/38731132/mysterious-embedded-null-byte-error) on StackOverflow, got an answer suggesting that one of the files in my virtualenv had an embedded null byte in its filename. I ended up running this command to find the culprit:

`find . -name "[^\x00]"`

That command turned up exactly one file:

`./lib/python3.5/site-packages/compressor/tests/static/css/url/2`

I pip uninstalled and then reinstalled django-compressor, but the find command turned up same file again. It appears that this file in django-compressor has a filename with a hidden character.

**Comment by shacker** [comment]
Following the debugging suggestion farther down on the SO page (modifying autoreload.py), the next time the crash happened I noticed that it returned:

`/path/to/virtualenvs/portal/lib/python3.5/site-packages/compressor/locale`

**Comment by karyon** [comment]
i didn't get the part with the second file, does that also have some weird bytes in there or does it have a different issue than the first one?

**Comment by shacker** [comment]
I'm not sure exactly. I suspect they're related. What I haven't done is to do a clean git checkout of the compressor codebase and do a `find` as above - whatever that turns up should be the answer.

**Comment by karyon** [comment]
after quite some time i realized (actually, @mrzzrm who knows this stuff better than i do told me) the regex you posted searches for files/directories that have exactly one char that is not the null byte (the ^ in there is a negation). since the "2" directory has only one char, it showed up. in fact, any directory or file with only one char will show up.

django-compressor also does not have any file or directory that's called "locale", but since autoreload appends "locale" to some directories (https://github.com/django/django/blob/master/django/utils/autoreload.py#L108-L115), that's where this path might come from.

so, i'm back at square one and have no idea where i should look. have you found the problem in the meantime?

**Comment by shacker** [comment]
Thanks for following up. No, we haven't found the problem elsewhere. Fortunately this has never shown up in production (only on some of our Macs) and is intermittent / occasional. So I'm not overly concerned. I'll post back if I figure out more. Thanks.

**Comment by karyon** [comment]
okay, i'm closing this as there is nothing we can do as far as i understand the matter. if you have any new insights, please get back to us :)
