### ISSUE TITLE
Same css and js files  but  get different file names in different server after compressing

### ISSUE THREAD

**Issue by wsYdd** [django-compressor/django-compressor#869]
I use offline compression to compress my static file(js and css).In different server I get different file names of css, but js file name is the same, Why?
one server 
![image](https://user-images.githubusercontent.com/11494521/29207152-adb508fc-7eb7-11e7-9614-7621641bc040.png)
another server
![image](https://user-images.githubusercontent.com/11494521/29207281-270b5288-7eb8-11e7-987a-1ceb932f51d8.png)

**Comment by diox** [comment]
See [`COMPRESS_CSS_HASHING_METHOD`](http://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_CSS_HASHING_METHOD).

**Comment by wsYdd** [comment]
COMPRESS_CSS_HASHING_METHOD I set None work，all right？

**Comment by diox** [comment]
It all depends on what you want to achieve and how everything is configured on your end. If you need the extra query string in the urls referenced in the css, then set it to `content` as per the docs I linked. If you don't need all that (because you already use something like `ManifestStaticFilesStorage` or equivalent) then yes, `None` works.

Either way, github issues are not a support forum. Read the docs, and if you need further help, I suggest opening up a thread on stackoverflow or something.
