### ISSUE TITLE
Doesn't keep space between multiple css selectors

### ISSUE THREAD

**Issue by broall** [django-compressor/django-compressor#897]
Hi, in my setting.py
`COMPRESS_ENABLED = True
COMPRESS_ROOT = os.path.join(BASE_DIR, 'static')
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSCompressorFilter',
    'compressor.filters.template.TemplateFilter',
    'compressor.filters.jsmin.JSMinFilter',
]`
`STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)`

In my css file:
`.class1  .class2 {}`

The compressed css is like this:
`.class1.class2{}`
which is wrong (space between two selectors) and changes the default styles. Could you help me please?

**Comment by karyon** [comment]
hi! i would say that the reason is either the `JSMinFilter` that is applied to css files, or it's a bug in one of the other filters. i would bet on the former. in the latter case, try removing the filters one by one to which one is responsible.

however, i need to ask you to use e.g. stackoverflow for support questions and the issuetracker here only for bug reports :)

**Comment by broall** [comment]
Thank you so much. I have removed `compressor.filters.jsmin.JSMinFilter` and it works! It seems that compress JS is turned on by default. 

Hope this issue could help someone in the future :)
